#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearlyBaked
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dwk-multiple-projects")]
	public partial class DomainSalesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DomainSalesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["dwk_multiple_projectsConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DomainSalesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DomainSalesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DomainSalesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DomainSalesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="ds.AddPotentialBuyer")]
		public int AddPotentialBuyer([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Domain", DbType="NVarChar(50)")] string domain, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Buyer", DbType="NVarChar(100)")] string buyer, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReferredBy", DbType="NVarChar(100)")] string referredBy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), domain, buyer, referredBy);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="ds.GetPotentialBuyers")]
		public ISingleResult<GetPotentialBuyersResult> GetPotentialBuyers([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Domain", DbType="NVarChar(50)")] string domain)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), domain);
			return ((ISingleResult<GetPotentialBuyersResult>)(result.ReturnValue));
		}
	}
	
	public partial class GetPotentialBuyersResult
	{
		
		private string _Buyer;
		
		private string _ReferredBy;
		
		public GetPotentialBuyersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Buyer", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Buyer
		{
			get
			{
				return this._Buyer;
			}
			set
			{
				if ((this._Buyer != value))
				{
					this._Buyer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReferredBy", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ReferredBy
		{
			get
			{
				return this._ReferredBy;
			}
			set
			{
				if ((this._ReferredBy != value))
				{
					this._ReferredBy = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
